env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - react-app
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  import/prefer-default-export: 1
  max-len: [2, { "code": 120 }]
  no-console: ["error", { allow: ["info", "error"] }]
  no-underscore-dangle: 1
  no-use-before-define: 0
  quotes: [2, double]
  react/destructuring-assignment: 1
  react/jsx-one-expression-per-line: 0
  react/jsx-tag-spacing: 1
  react/prop-types: 1
  react/sort-comp: 1
  react/state-in-constructor: [2, never]
